services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ch-users-service:latest
    ports:
      - "9001:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/CH-UsersDB
      SPRING_R2DBC_USERNAME: chuser
      SPRING_R2DBC_PASSWORD: ch-password
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/CH-UsersDB
      SPRING_FLYWAY_USER: chuser
      SPRING_FLYWAY_PASSWORD: ch-password
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: chuser
      POSTGRES_PASSWORD: ch-password
      POSTGRES_DB: CH-UsersDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chuser -d CH-UsersDB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata: